name: SaveItems
main: SaveItems\main
version: 1.0.0
api: 5.0.0
author: FurryJaki1992

commands:
  savesitem:
    description: 'Lưu trữ vật phẩm trong kho'
    permission: savesitem.cmd
permissions:
  savesitem.cmd:
    default: op
