name: SaveItems
main: SaveItems\main
version: 1.0.0
api: 5.0.0
author: FurryJaki1992

commands:
  saveitems:
    description: 'Lưu trữ vật phẩm vào kho'
    permission: saveitems.cmd
  takeitems:
    description: 'Lấy vật phẩm trong kho'
    permission: saveitems.cmd
permissions:
  saveitems.cmd:
    default: true
  takeitems.cmd:
    default: true
